import org.scalatest.FunSuite

class ProblemSolverTest extends FunSuite {

  test(
    """1 - If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
      |Find the sum of all the multiples of 3 or 5 below 1000.""".stripMargin
  ) {

    assert(ProblemSolver.problem1(10) === 23)
  }

  test(
    """2 - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
      |1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
      |By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.""".stripMargin
  ) {

    assert(ProblemSolver.problem2(100) === 188)
  }

  test(
    """5 - 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
      |What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?""".stripMargin
  ) {

    assert(ProblemSolver.problem5(10) === 2520)
  }

  test(
    """6 - The sum of the squares of the first ten natural numbers is,
      |
      |The square of the sum of the first ten natural numbers is,
      |
      |Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is .
      |
      |Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.""".stripMargin
  ) {

    assert(ProblemSolver.problem6(10) === 2640)
  }

  test(
    """21 - Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
      |If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers.
      |
      |For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.
      |
      |Evaluate the sum of all the amicable numbers under 10000.""".stripMargin
  ) {

    assert(ProblemSolver.problem21(1000) === 504)
  }
}
